
#!/bin/bash
threshold=90
# Monitor CPU usage and trigger alert if threshold exceeded
cpu_usage=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | cut -d. -f1)
if [ "$cpu_usage" -gt "$threshold" ]; then
echo "High CPU usage detected: $cpu_usage%"
# Add alert/notification logic here
fi



<<arun
top -bn1: Runs the top command in batch mode (-b) for one iteration (-n1).
grep "Cpu(s)": Searches for the line containing "Cpu(s)" which has the CPU usage information.
awk '{print $2}': Extracts the second field from the grep output, which represents the CPU idle percentage.
cut -d. -f1: Cuts the extracted value at the decimal point and takes the first part, effectively converting the float to an integer by truncating the decimal part
%Cpu(s):  0.0 us,  4.8 sy,  0.0 ni, 95.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
This line from the top command output shows the current CPU usage statistics in terms of the percentage of CPU time spent in various states. Here's what each part means:

%Cpu(s): Indicates that the following values are percentages of total CPU time.

0.0 us: Percentage of CPU time spent in user space (non-kernel code). This includes all normal processes executed by users.

4.8 sy: Percentage of CPU time spent in kernel space (system code). This includes all system processes and kernel operations.

0.0 ni: Percentage of CPU time spent on processes with a manually set nice value (priority). This represents "niced" processes, which have their priority adjusted to be less favorable.

95.2 id: Percentage of CPU time spent idle. This represents the time when the CPU is not doing any work and is idle.

0.0 wa: Percentage of CPU time spent waiting for I/O operations to complete. This includes time the CPU is waiting for disk or network I/O.

0.0 hi: Percentage of CPU time servicing hardware interrupts. These are interrupts generated by hardware devices that require immediate attention from the CPU.

0.0 si: Percentage of CPU time servicing software interrupts. These are interrupts generated by software conditions that require CPU attention.

0.0 st: Percentage of CPU time stolen from this virtual machine by the hypervisor for other tasks (in virtualized environments). This represents the time that the virtual CPU was ready to run but wasn't allowed to because the hypervisor was using the physical CPU for other purposes.
arun
